name: Add a new paper
description: Add a new human-AI system paper to the list of Annotated papers on the SPHERE website.
title: "Add a new paper [System Name]"
labels: new paper
assignees: 
 - dorazhao99
 - mqo00
body:
  - type: input
    id: title
    attributes:
      label: Paper Title
      placeholder: "ex. AI Chains: Transparent and Controllable Human-AI Interaction by Chaining Large Language Model Prompts"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Paper URL
      placeholder: ex. https://doi.org/10.1145/3491102.3517582
    validations:
      required: true
  - type: input
    id: year
    attributes:
      label: Paper Year
      placeholder: ex. 2022
    validations:
      required: true
  - type: input
    id: venue
    attributes:
      label: Paper Venue (HCI or NLP)
      placeholder: ex. HCI
    validations:
      required: true
  - type: textarea
    id: sphere-text
    attributes:
      label: SPHERE Eval Card Text
      description: The answer to what, how, who, when, meta-how evaluation questions.
      placeholder: See our paper.
    validations:
      required: false
  - type: input
    id: what-component
    attributes:
      label: Aspects for what-component
      placeholder: ex. model, system
    validations:
      required: true
  - type: input
    id: what-design-goal
    attributes:
      label: Aspects for what-design-goal
      placeholder: ex. effectiveness, efficiency, satisfaction
    validations:
      required: true
  - type: input
    id: how-scope
    attributes:
      label: Aspects for how-scope
      placeholder: ex. intrinsic, extrinsic
    validations:
      required: true
  - type: input
    id: how-method
    attributes:
      label: Aspects for how-method
      placeholder: ex. quantitative, qualitative
    validations:
      required: true
  - type: input
    id: who-human
    attributes:
      label: Aspects for who-human
      placeholder: ex. expert, user
    validations:
      required: true
  - type: input
    id: who-automated
    attributes:
      label: Aspects for who-automated
      placeholder: ex. static, generative
    validations:
      required: true
  - type: input
    id: when-timescale
    attributes:
      label: Aspects for when-timescale
      placeholder: ex. instant, shortterm, longterm
    validations:
      required: true
  - type: input
    id: meta-how-validation
    attributes:
      label: Aspects for meta-how-validation
      placeholder: ex. validity, reliability
    validations:
      required: true